// Authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

// Books
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const SET_LOADING = "SET_LOADING";
export const SEARCH_BOOKS = "SEARCH_BOOKS";
export const FILTER_BOOKS = "FILTER_BOOKS";
export const FETCH_RECOMMENDED_BOOKS_SUCCESS = "FETCH_RECOMMENDED_BOOKS_SUCCESS";
export const FETCH_RECOMMENDED_BOOKS_FAILURE = "FETCH_RECOMMENDED_BOOKS_FAILURE";

export const REMOVE_RECOMMENDATIONS = "REMOVE_RECOMMENDATIONS"
export const REMOVE_FILTERS = "REMOVE_FILTERS"